/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package learnmode;

import static gamechess.GameChess.Interface;

/**
 *
 * @author Admin
 */
public class LearnModeScreen extends javax.swing.JFrame {

    /**
     * Creates new form LearnModeScreen
     */
    public LearnModeScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PawnLearn = new javax.swing.JButton();
        KnightLearn = new javax.swing.JButton();
        RookLearn = new javax.swing.JButton();
        BishopLearn = new javax.swing.JButton();
        QueenLearn = new javax.swing.JButton();
        KingLearn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CapturingLearn = new javax.swing.JButton();
        NotationLearn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CheckLearn = new javax.swing.JButton();
        GetOutLearn = new javax.swing.JButton();
        StalemateLearn = new javax.swing.JButton();
        CheckmateLearn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        CastlingQueenLearn = new javax.swing.JButton();
        PromotionLearn = new javax.swing.JButton();
        EnPassantLearn = new javax.swing.JButton();
        CastlingKingLearn = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 153));

        jPanel3.setBackground(new java.awt.Color(190, 138, 59));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(153, 102, 0)));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MOVES");

        PawnLearn.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        PawnLearn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bp.png"))); // NOI18N
        PawnLearn.setText("Pawn");
        PawnLearn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PawnLearnActionPerformed(evt);
            }
        });

        KnightLearn.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        KnightLearn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bN.png"))); // NOI18N
        KnightLearn.setText("Knight");
        KnightLearn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KnightLearnActionPerformed(evt);
            }
        });

        RookLearn.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        RookLearn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bR.png"))); // NOI18N
        RookLearn.setText("Rook");
        RookLearn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RookLearnActionPerformed(evt);
            }
        });

        BishopLearn.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        BishopLearn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bB.png"))); // NOI18N
        BishopLearn.setText("Bishop");
        BishopLearn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BishopLearnActionPerformed(evt);
            }
        });

        QueenLearn.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        QueenLearn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bQ.png"))); // NOI18N
        QueenLearn.setText("Queen");
        QueenLearn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QueenLearnActionPerformed(evt);
            }
        });

        KingLearn.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        KingLearn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bK.png"))); // NOI18N
        KingLearn.setText("King");
        KingLearn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KingLearnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(QueenLearn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PawnLearn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BishopLearn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(KnightLearn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RookLearn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(KingLearn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(140, 140, 140))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PawnLearn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KnightLearn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RookLearn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BishopLearn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QueenLearn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KingLearn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(190, 138, 59));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(153, 102, 0)));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BASIC CONCEPTS");

        CapturingLearn.setBackground(new java.awt.Color(204, 255, 204));
        CapturingLearn.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        CapturingLearn.setText("Capturing");
        CapturingLearn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapturingLearnActionPerformed(evt);
            }
        });

        NotationLearn.setBackground(new java.awt.Color(204, 255, 204));
        NotationLearn.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        NotationLearn.setText("Notation");
        NotationLearn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotationLearnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CapturingLearn, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(NotationLearn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel2)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(CapturingLearn)
                .addGap(28, 28, 28)
                .addComponent(NotationLearn)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(190, 138, 59));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(153, 102, 0)));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CHECK");

        CheckLearn.setBackground(new java.awt.Color(204, 255, 204));
        CheckLearn.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        CheckLearn.setText("Check");
        CheckLearn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckLearnActionPerformed(evt);
            }
        });

        GetOutLearn.setBackground(new java.awt.Color(204, 255, 204));
        GetOutLearn.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        GetOutLearn.setText("Getting out of check");
        GetOutLearn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetOutLearnActionPerformed(evt);
            }
        });

        StalemateLearn.setBackground(new java.awt.Color(204, 255, 204));
        StalemateLearn.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        StalemateLearn.setText("Stalemate");
        StalemateLearn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StalemateLearnActionPerformed(evt);
            }
        });

        CheckmateLearn.setBackground(new java.awt.Color(204, 255, 204));
        CheckmateLearn.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        CheckmateLearn.setText("Checkmate");
        CheckmateLearn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckmateLearnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CheckLearn, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(GetOutLearn, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckmateLearn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StalemateLearn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(127, 127, 127))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckLearn)
                    .addComponent(CheckmateLearn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GetOutLearn)
                    .addComponent(StalemateLearn))
                .addGap(94, 94, 94))
        );

        jPanel4.setBackground(new java.awt.Color(190, 138, 59));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(153, 102, 0)));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SPECIAL MOVES");

        CastlingQueenLearn.setBackground(new java.awt.Color(204, 255, 204));
        CastlingQueenLearn.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        CastlingQueenLearn.setText("Castling - Queen side");
        CastlingQueenLearn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CastlingQueenLearnActionPerformed(evt);
            }
        });

        PromotionLearn.setBackground(new java.awt.Color(204, 255, 204));
        PromotionLearn.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        PromotionLearn.setText("Promotion");
        PromotionLearn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PromotionLearnActionPerformed(evt);
            }
        });

        EnPassantLearn.setBackground(new java.awt.Color(204, 255, 204));
        EnPassantLearn.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        EnPassantLearn.setText("En Passant");
        EnPassantLearn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnPassantLearnActionPerformed(evt);
            }
        });

        CastlingKingLearn.setBackground(new java.awt.Color(204, 255, 204));
        CastlingKingLearn.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        CastlingKingLearn.setText("Castling - King side");
        CastlingKingLearn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CastlingKingLearnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CastlingKingLearn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CastlingQueenLearn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PromotionLearn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EnPassantLearn, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(CastlingKingLearn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CastlingQueenLearn)
                .addGap(18, 18, 18)
                .addComponent(PromotionLearn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(EnPassantLearn)
                .addGap(18, 18, 18))
        );

        Back.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel5.setText("SELECT A LESSON TO LEARN");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Back)
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addGap(287, 287, 287))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(Back))
                        .addGap(28, 28, 28)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PawnLearnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PawnLearnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PawnLearnActionPerformed

    private void KnightLearnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KnightLearnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KnightLearnActionPerformed

    private void RookLearnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RookLearnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RookLearnActionPerformed

    private void BishopLearnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BishopLearnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BishopLearnActionPerformed

    private void QueenLearnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QueenLearnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QueenLearnActionPerformed

    private void KingLearnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KingLearnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KingLearnActionPerformed

    private void CapturingLearnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapturingLearnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapturingLearnActionPerformed

    private void NotationLearnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotationLearnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NotationLearnActionPerformed

    private void CheckLearnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckLearnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckLearnActionPerformed

    private void GetOutLearnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetOutLearnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GetOutLearnActionPerformed

    private void StalemateLearnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StalemateLearnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StalemateLearnActionPerformed

    private void CheckmateLearnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckmateLearnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckmateLearnActionPerformed

    private void CastlingKingLearnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CastlingKingLearnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CastlingKingLearnActionPerformed

    private void CastlingQueenLearnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CastlingQueenLearnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CastlingQueenLearnActionPerformed

    private void PromotionLearnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PromotionLearnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PromotionLearnActionPerformed

    private void EnPassantLearnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnPassantLearnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnPassantLearnActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        Interface();
        dispose();
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LearnModeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LearnModeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LearnModeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LearnModeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LearnModeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton BishopLearn;
    private javax.swing.JButton CapturingLearn;
    private javax.swing.JButton CastlingKingLearn;
    private javax.swing.JButton CastlingQueenLearn;
    private javax.swing.JButton CheckLearn;
    private javax.swing.JButton CheckmateLearn;
    private javax.swing.JButton EnPassantLearn;
    private javax.swing.JButton GetOutLearn;
    private javax.swing.JButton KingLearn;
    private javax.swing.JButton KnightLearn;
    private javax.swing.JButton NotationLearn;
    private javax.swing.JButton PawnLearn;
    private javax.swing.JButton PromotionLearn;
    private javax.swing.JButton QueenLearn;
    private javax.swing.JButton RookLearn;
    private javax.swing.JButton StalemateLearn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
